### ISSUE TITLE
Animated text animations not working when interpolation is on

### ISSUE THREAD

**Issue by IceandFire04** [PenguinMod/PenguinMod-Vm#36] opened 2023-10-07 10:00 UTC
yeah, not much else really

**Comment by IceandFire04** [comment] 2023-10-07 10:01
scratch that, the entire extension just doesn't work :/

**Comment by JoshAtticus** [comment] 2023-11-10 05:43
Not a PenguinMod problem, this affects Turbowarp too

**Comment by JeremyGamer13** [comment] 2023-11-10 05:44
this shouldnt be closed if the issue is still present, regardless of if the issue is also in TW

**Comment by JoshAtticus** [comment] 2023-11-10 05:45
> this shouldnt be closed if the issue is still present, regardless of if the issue is also in TW

Yes but it does not affect specifically us and should be moved to the Turbowarp-VM repo or the PenguinMod-VM repo

**Comment by IceandFire04** [comment] 2023-11-10 23:33
Actually, it does. On turbowarp, lilymakesthings' animated text works fine with interpolation, but the neither work on pm, even after changing extension ids

**Comment by JoshAtticus** [comment] 2023-11-11 04:25
Ah ok, I'll keep this open then

**Comment by AD1340** [comment] 2024-04-28 02:45
for me the animated text extension works but it glitches out

**Comment by SharkPool-SP** [comment] 2024-04-28 02:51
> for me the animated text extension works but it glitches out

wdym

**Comment by SharkPool-SP** [comment] 2024-04-28 02:51
> yeah, not much else really

also this should be fixed, interpolation has been fixed recently

**Comment by IceandFire04** [comment] 2024-05-01 10:47
Alright. I'll check later and close this as completed sooner or later

**Closed as completed** 2024-07-17 07:14 UTC
